### Sum
POST http://localhost:8080/math/sum/10/10
Accept: application/json
Content-Type: application/json; charset=utf-8

### Subtraction
POST http://localhost:8080/math/sub/10/10
Accept: application/json
Content-Type: application/json; charset=utf-8

### Division
POST http://localhost:8080/math/div/10/10
Accept: application/json
Content-Type: application/json; charset=utf-8

### Multiplication
POST http://localhost:8080/math/mult/10/10
Accept: application/json
Content-Type: application/json; charset=utf-8