version: '3.5'
services:
  api:
    container_name: java-rest-api.api
    build:
      context: .
    image: java-rest-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /tmp
    depends_on:
      - database
  database:
    container_name: java-rest-api.db
    image: mysql:8
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4306:3306"

networks:
  default:
    name: "java-rest-api"
