version: '3.5'
services:
  api:
    container_name: java-rest-api.api
    build:
      context: .
      target: build
    entrypoint: mvn spring-boot:run
    env_file: .env
    image: java-rest-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - .:/app
  database:
    container_name: java-rest-api.db
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - "4306:3306"
  database-ui:
    image: phpmyadmin
    container_name: java-rest-api.db-ui
    restart: always
    environment:
      - PMA_HOST=database
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "4307:80"
    depends_on:
      - api

networks:
  default:
    name: "java-rest-api"
