@id = my_person_id_here

### Update name
PATCH http://localhost:8080/person/{{id}}
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "name": "Anthony Stark Updated"
}

### Update email
PATCH http://localhost:8080/person/{{id}}
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "email": "tony_v2@stark.com"
}

### Update all
PATCH http://localhost:8080/person/{{id}}
Accept: application/json
Content-Type: application/json; charset=utf-8

{
  "name": "Anthony Stark Updated all",
  "email": "tony_v3@stark.com"
}
